binding_ip = "0.0.0.0"
port = 9292
secret_key_base = ""
rails_env = "production"
threads = 5
concurrency = 1
puma_pidfile = './tmp/pids/puma.pid'
worker_timeout = 240

[database]
name = "feeder_production"
username = "feeder"
password = ""
pool = 5
timeout = 5000
host = "127.0.0.1"
port = 5432

[redis]
host = "localhost"
port = "6379"

[sidekiq]
verbose = false
logfile = "/var/log/sidekiq.log"
pidfile = "/var/run/sidekiq.pid"
concurrency = 1
[[sidekiq.queues]]
name = "default"
priority = 5
[[sidekiq.queues]]
name = "high"
priority = 1
[[sidekiq.queues]]
name = "low"
priority = 10